path: /content/drive/MyDrive/University/AOI/OpenAOI/openAOI/dataset/prepared_dataset
train: /content/drive/MyDrive/University/AOI/OpenAOI/openAOI/dataset/prepared_dataset/train/images
val: /content/drive/MyDrive/University/AOI/OpenAOI/openAOI/dataset/prepared_dataset/val/images
test: /content/drive/MyDrive/University/AOI/OpenAOI/openAOI/dataset/prepared_dataset/test/images
names:
  0: SolderSlopeDefect
  1: SolderBridgingDefect
